name: LoJack Integration
description: Track the location of your LoJack-enabled devices in Home Assistant.
author: Devin Slick
repository: https://github.com/devinslick/lojack-homeassistant
category: integration